version:  '3.8'
services:
  androidstudio:
    build: .
    image: myandroid
    privileged: true  # this is not safe, BE CARFEFUL !
    environment:
      DISPLAY: ${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - ./projects/:/root/AndroidStudioProjects/
    container_name: androidstudio
